AWSTemplateFormatVersion: 2010-09-09
Transform:
  - SsmReplace
Resources:
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "{{/projects/foo}}"
  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "{{/projects/bar,optional-default-value}}"
